name: release
on: 
  workflow_run: 
    branches: [release]
    workflows: [master]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/download-artifact@v3
          with:
            name: package
            path: dist

        - uses: nuget/setup-nuget@v1
          with:
              nuget-version: '6.x'
              nuget-api-key: ${{secrets.NUGET_API_KEY}}

