name: release
on: 
  push: { branches: [release] }

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/download-artifact@v3
          with:
            name: package
            path: dist